### ISSUE TITLE
ENH: general feedback on pydarshan summary text

### ISSUE THREAD

**Issue by carns** [darshan-hpc/darshan#641]
Hopefully this is legible; it's easier for me to review the report as a whole than offer feedback on individual components at a time:

https://acrobat.adobe.com/link/track?uri=urn:aaid:scds:US:fc9ed5ea-c0fe-48b0-9502-b24208a1742d

The only organizational change is a suggestion to reorg the top two sections slightly so that all of the generic job metadata is in one section and all of the Darshan instrumentation metadata is in another section.  The rest of the edits are just wording suggestions.

The re-write of the caption for the I/O cost figure is an attempt to mitigate (for now) the concern that the average values can be misleading, by referring back to the heatmap which can show imbalance.  We might want to change this again later once we have the tooling to show the slowest process in addition to the average process.

Any of this is open for discussion.

**Comment by tylerjereddy** [comment]
Thanks, we could probably edit your issue message to contain a markdown checklist for the items, then have granular PRs to address the items individually (to make it easier for review of changes).

**Comment by nawtrey** [comment]
Thanks for the feedback! I think this covers Phil's comments:

#### TODO: 
- [ ] "Log Details" -> "Job Summary"
- [ ] Change runtime data type to integer
- [ ] In "Log Details", "Command" -> "Command Line"
- [ ] Break up log metadata/module info such that "Log Filename", "Runtime Library Version" and "Log Format Version" are combined with the "Module Breakdown" metadata, with the module data on top
- [ ] "Module Breakdown" -> "Darshan Log Information"
- [ ] Suffix each module index with "Module Data" (i.e. `POSIX (ver=4)` -> `POSIX (ver=4) Module Data`)
- [ ] Update partial flag message to "Module data incomplete due to runtime memory or record count limit"
- [ ] "I/O Operations" -> "I/O Summary"
- [ ] DXT heatmap caption:
   * "vertical bar graph" -> "top edge bar graph"
   * Remove "all" from "across all ranks"
   * "show the total I/O" -> "aggregate I/O volume"
   * "horizontal bar graph" -> "right edge bar graph"
   * "all I/O events for each rank to illustrate how th eI/O was distributed across ranks" -> "each rank across time slices t show I/O distribution across ranks"
- [ ] Update I/O cost caption to "Average (across all ranks) amount of run time that each process spent performing I/O, broken down by access type. See the right edge bar graph on heat maps in preceding section to indicate if I/O activity was balanced across processes."
- [ ] "Per-Module Stats" -> "Per-Module Statistics"
- [ ] Add link to Darshan website (not documentation) in the report footer

I'm not completely sure I understand _exactly_ how we want the log metadata/module data setup, but otherwise it makes sense to me. I don't feel strongly about the caption wording or titles of any of these things so I'm happy to just make the suggested changes.

**Comment by carns** [comment]
Thanks, that looks right to me.  I can probably help refine further by submitting PRs myself once these are in place.

One more (this figure was not yet present in the example I printed but I just found in a different issue):

[ ] access size figure caption: "Read/write operations grouped by access size. Most frequent access sizes are featured in the Common Access Sizes table." --> "Histogram of read and write access sizes.  The specific values of the most frequently occurring access sizes can be found in the Common Access Sizes table."

**Comment by nawtrey** [comment]
@carns can you confirm if this is the new metadata organization you are suggesting? I followed my original understanding (in the task above) but after reviewing the document you posted I'm not certain I am swapping the correct things. 

![Screen Shot 2022-02-16 at 11 18 18 AM](https://user-images.githubusercontent.com/46797896/154333525-67fedbd4-b98c-4d6e-a9bb-e4c2f994e547.png)

**Comment by carns** [comment]
That's what I was thinking @nawtrey .  My only other suggestion would be to put the last three rows in the "Darshan Log Information" section first in that section (so it leads off with the name and version numbers, then lists all of the modules).  The grouping is good though.

**Comment by nawtrey** [comment]
Sounds good! I'll try to get this finished today then.

**Comment by tylerjereddy** [comment]
Should be done now after gh-670.
